### ISSUE TITLE
The resume data is invalid 

### ISSUE THREAD

**Issue by Alger** [Heikowi/HWIFileDownload#11]
crash and restart the app, the resume data is invaid, do you have some ideas to fix this issue?

http://stackoverflow.com/questions/28360750/nsurlsession-with-invalid-resume-data

**Comment by Heikowi** [comment]
NSFileManager offers a function for accessing paths relative to the private app container:

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/index.html#//apple_ref/occ/instm/NSFileManager/URLsForDirectory:inDomains:

These directories are morst important for storing private data within the app container:

NSLibraryDirectory
NSDocumentDirectory
NSCachesDirectory

Here is a discussion and some help on stackoverflow concerning storing data with an ios app:
http://stackoverflow.com/questions/1567134/how-can-i-get-a-writable-path-on-the-iphone

When using a persistent storage location for resume data you might want to purge the data on low storage space conditions.


Hope this helps.

Best
Heiko
