### ISSUE TITLE
403 pages downloaded

### ISSUE THREAD

**Issue by tcalin** [Heikowi/HWIFileDownload#12]
Hi!
I am trying to find an elegant solution to prevent my app from downloading 403 pages instead of the right files. I saw in documentation there is an optional delegate method

`- (BOOL)httpStatusCode:(NSInteger)aHttpStatusCode isValidForDownloadIdentifier:(nonnull NSString *)aDownloadIdentifier;`

but I can not find it.
Any help will be useful.
Thanks!

**Comment by tcalin** [comment]
Found it in master branch.

**Comment by Heikowi** [comment]
Good.
