### ISSUE TITLE
Not Resuming on Relaunch of Sample App

### ISSUE THREAD

**Issue by mowebkrunal** [Heikowi/HWIFileDownload#13]
I was looking for this solution but I have download and Run this App for First time start download of 1.tiff & 2.tiff. Now put in Background and Terminate Application. Relaunch Application shows "Started with no progress". but doesn't start or resume download for some how.

**Comment by Heikowi** [comment]
There was an issue with interrupted downloads on iOS 6. I fixed the issue now.
W.r.t. expectations about download resuming behavior please take a look at the section "Workflows and Scenarios" on the ReadMe page.

**Comment by harshal-wani** [comment]
I tried to restart app on relaunch but did not work.
Could you please help?
