### ISSUE TITLE
The downloading status seems weird after hitting the "crash" button while some tasks are not finished

### ISSUE THREAD

**Issue by expkzb** [Heikowi/HWIFileDownload#20]
The downloading progress on the top is increasing but nothing changed in the list. The tasks those were not finished are marked as "cancelled". I think they are still active since they become "completed" in a few minutes.

**Comment by swapnil-vuclip** [comment]
I am facing the same issue when ongoing downloading and app get crashed, I relaunch the app the downloading progress on the top is increasing but I am getting isDownloadingIdentifier status to fails but actually the downloading  happening

**Comment by Heikowi** [comment]
Unable to reproduce.
