### ISSUE TITLE
some of goDady server url return -1

### ISSUE THREAD

**Issue by nitingohel** [Heikowi/HWIFileDownload#21]
I just download fine using [HWIFileDownload](url) that some of GoDaddy server url that aTotalBytesExpectedToWriteCount return in -1 how to solve it

**Comment by Heikowi** [comment]
It's a server issue. The server does not provide the necessary information for progress display (the expected file size).

**Comment by nitingohel** [comment]
No that not a server issue if that same url used at another code that code is working please dont close issue
