### ISSUE TITLE
I wanna  know that how to store the filePath for every DemoDownloadItem

### ISSUE THREAD

**Issue by mobyzhang** [Heikowi/HWIFileDownload#22]
Thx for the Demo,I add a property for the DemoDownloadItem interface, after I download the file ,I wanna store the filePath for every DemoDownloadItem. Could u pls tell me how to implement it? And I wanna initialize the downloadItemsArray from the internet ,maybe not 11 pieces of datas , I wanna know how to apply the downloadIdentifier for every item?

**Comment by Heikowi** [comment]
The local file URL is passed along with the delegate call
`- (void)downloadDidCompleteWithIdentifier:(nonnull NSString *)aDownloadIdentifier
                             localFileURL:(nonnull NSURL *)aLocalFileURL`
Please take a look at DemoDownloadStore.m:144

Initializing the downloadItemsArray is a client task. A working example is supplied with the Demo app. Individual requirements might be different.
