### ISSUE TITLE
Can HWIFileDownloader Init Fail?

### ISSUE THREAD

**Issue by TosinAF** [Heikowi/HWIFileDownload#24]
Hey, 

Great work on this. I wanted to find out if HWIFileDownloader Init can fail? If not I will submit a PR to fix that for swift. I checked the code and it didn't seem like it could.

Cheers

**Comment by Heikowi** [comment]
Thanks for your feedback!
Well, HWIFileDownloader's init will return nil if `[super init]` fails. But I think it's a debated topic.
I tend to think, crashing the app in the unlikely, contrived case of a failure simplifies things here.
So, please send your PR, sounds good.

**Comment by Heikowi** [comment]
Fixed with b23fa64c893f4a4de457647ca08e5e6203250280.
