### ISSUE TITLE
How do I get download progress in Interrupted state

### ISSUE THREAD

**Issue by swapnil-vuclip** [Heikowi/HWIFileDownload#25]
Thx for the Demo, I want the download progress to show on UI under below two condition
- I started download and suppose after  50% download  network goes disconnected then after I kill the app and relaunch the app In that case I want to show the download percentage But I get zero value in DemoDownloadItem object
- 2nd one is the same above scenario but only change is when app gets crashed

**Comment by Heikowi** [comment]
Please note that an system bug with iOS 10 prevented correct progress reporting after resuming until iOS 10.2.
Do you experience issues still with iOS 10.2?
