### ISSUE TITLE
I want to set network type allowed for the download.

### ISSUE THREAD

**Issue by hb2708** [Heikowi/HWIFileDownload#27]
Hello @Heikowi ,

Can I implement the download manager in following way?
Like while starting download user can set allowed network type for the specific download item.

Such as wifi and cellular network.

So if the user has selected wifi only for one download item and user switches to cellular then the download will automatically get paused. And when we switch back to wifi so download will get started/resumed

Please let me know

**Comment by Heikowi** [comment]
Search for
`- (void)customizeBackgroundSessionConfiguration:(nonnull NSURLSessionConfiguration *)aBackgroundSessionConfiguration`
If implemented, this method will be called on the delegate to allow customization of the configuration.
You can set the download to wifi-only like this:
`aBackgroundSessionConfiguration.allowsCellularAccess = NO;`
