### ISSUE TITLE
Why use “mutableCopy” method？？？？？

### ISSUE THREAD

**Issue by weiyongqiang** [Heikowi/HWIFileDownload#31]
https://github.com/Heikowi/HWIFileDownload/blob/252bf0cd077dbcab9591dda7f350eff7b62948e6/Demo/HWIFileDownload/DemoDownloadStore.m#L124

**Comment by Heikowi** [comment]
Thanks for the hint. Fixed with 3ada7a327aa21f53b10581e2c4d33b1154f7e4ca.
