### ISSUE TITLE
New code not in v3.1 release

### ISSUE THREAD

**Issue by ddfreiling** [Heikowi/HWIFileDownload#34]
Hello @Heikowi 

It seems to me that version 3.1 of this excellent library does not contain the new option to customize the urlRequest. The `3.1` tag is still on a much older commit than I think it was meant to. If this is intentional, I would love to see a release with the `urlRequestForRemoteURL` callback that works on all iOS versions.

Thanks in advance!

**Comment by Heikowi** [comment]
Thanks a lot for pointing this out!
I just released `3.2` with all the latest code changes.
