### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by VSG24** [Heikowi/HWIFileDownload#35]
How can I use this in Swift 4?

**Comment by Heikowi** [comment]
Is Apple's documentation of no help?
[Using Swift with Cocoa and Objective-C (Swift 4.0.3)](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/index.html#//apple_ref/doc/uid/TP40014216-CH2-ID0)
