### ISSUE TITLE
file name generated

### ISSUE THREAD

**Issue by syrakozz** [Heikowi/HWIFileDownload#7]
@Heikowi 
i always put a identifer as number 
but the downloaded filename is like this 
063BF1C1-EFF9-4E66-8EB1-20FF24368A55.mp3
how its generated, and how i can changed ?
thank you

**Comment by syrakozz** [comment]
i get it finaly,
but could you plz make 
+ (NSURL *)fileDownloadDirectoryURL 
a public method so i can access it ,

**Comment by Heikowi** [comment]
fileDownloadDirectoryURL now is public.
