### ISSUE TITLE
download timeout

### ISSUE THREAD

**Issue by syrakozz** [Heikowi/HWIFileDownload#8]
in some case the download link expire after certain, time 
could you plz add some notification logic maybe, so we can detect if the link sudnely become dead, or its not reponding so i can swtich the new download link

**Comment by Heikowi** [comment]
NSApplicationSupportDirectory is used as default download directory (with attribute NSURLIsExcludedFromBackupKey). Files inside this directory are not cleaned by the system (in contrast to NSCachesDirectory). 
http://stackoverflow.com/questions/12371321/where-should-i-save-data-files-i-want-to-keep-long-term-and-how-do-i-prevent
What do you mean with "download link expires"?

**Comment by syrakozz** [comment]
by download link expire i mean links like the old rapid share or some file host site, 
he will give you a link to download on certain time and after that the link will be dead, what i tring to do, is to make a time out for it and then make it continue from a new link

**Comment by Heikowi** [comment]
This business logic goes far beyond simple file downloading. HWIFileDownload just simplifies triggering and receiving file download data. This is something you have to model in your application code.
